spring:
  profiles.active: default
---
spring:
  profiles: default

default-films:
  films:
    0 :
      id: 0
      filmName: Spider-Man Homecoming
      description: Peter Parker attempts to balance his life in high school with his career as the web-slinging superhero Spider-Man.
    1 :
      id: 1
      filmName: "Transformers: The Last Knight"
      description: Optimus Prime finds his home planet, Cybertron, now a dead planet, in which he comes to find he was responsible for killing. He finds a way to bring the planet back to life, but in order to do so, he needs to find an artifact, which is on Earth.
    2 :
      id: 2
      filmName: Despicable Me 3
      description: Gru meets his twin brother Dru he never knew about.
    3 :
      id: 3
      filmName: Wonder Woman
      description: Before she was Wonder Woman she was Diana, princess of the Amazons, trained warrior. When a pilot crashes and tells of conflict in the outside world, she leaves home to fight a war to end all wars, discovering her full powers and true destiny.

default-theatres:
  theatres:
    0 :
      id: 0
      rows: 10
      columns: 20
    1 :
      id: 1
      rows: 15
      columns: 20
    2 :
      id: 2
      rows: 15
      columns: 20

default-film-showings:
  filmShowings:
    0 :
      id: 0
      filmId: 0
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00
    1 :
      id: 1
      filmId: 0
      theatreId: 2
      dateTimeStr: 2018-01-01 01:00
    2 :
      id: 2
      filmId: 0
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00
    3 :
      id: 3
      filmId: 1
      theatreId: 1
      dateTimeStr: 2018-01-01 01:00
    4 :
      id: 4
      filmId: 1
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00
    5 :
      id: 5
      filmId: 1
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00
    6 :
      id: 6
      filmId: 2
      theatreId: 2
      dateTimeStr: 2018-01-01 01:00
    7 :
      id: 7
      filmId: 2
      theatreId: 2
      dateTimeStr: 2018-01-01 01:00
    8 :
      id: 8
      filmId: 2
      theatreId: 2
      dateTimeStr: 2018-01-01 01:00
    9 :
      id: 19
      filmId: 3
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00
    10 :
      id: 10
      filmId: 3
      theatreId: 1
      dateTimeStr: 2018-01-01 01:00
    11 :
      id: 11
      filmId: 3
      theatreId: 0
      dateTimeStr: 2018-01-01 01:00

default-film-showing-mapping:
  filmShowingMapping:
    0 :
      0, 1, 2
    1 :
      3, 4, 5
    2 :
      6, 7, 8
    3 :
      9, 10, 11